version: "3"
services:
  node-app:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: mysql@123
      MYSQL_DATABASE: zscan-desafio
    ports:
      - "3395:3306"
